# Generated by Django 5.0.4 on 2024-04-23 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='is_mentor',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='status',
            field=models.CharField(choices=[('PR', 'Проектант'), ('MT', 'Наставник')], default='PR', max_length=20),
        ),
        migrations.AlterField(
            model_name='commentary',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='question',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='question',
            name='specialization_1',
            field=models.CharField(choices=[('TL', 'Teamlead'), ('BE', 'Backend'), ('FE', 'Frontend'), ('DS', 'Дизайн'), ('AL', 'Аналитика')], max_length=20),
        ),
        migrations.AlterField(
            model_name='question',
            name='specialization_2',
            field=models.CharField(choices=[('TL', 'Teamlead'), ('BE', 'Backend'), ('FE', 'Frontend'), ('DS', 'Дизайн'), ('AL', 'Аналитика')], max_length=20),
        ),
        migrations.AlterField(
            model_name='question',
            name='specialization_3',
            field=models.CharField(choices=[('TL', 'Teamlead'), ('BE', 'Backend'), ('FE', 'Frontend'), ('DS', 'Дизайн'), ('AL', 'Аналитика')], max_length=20),
        ),
        migrations.AlterField(
            model_name='question',
            name='status',
            field=models.CharField(choices=[('NK', 'Нет комментариев'), ('NA', 'Не решён'), ('AF', 'Решён')], default='Нет комментариев', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='specialization_1',
            field=models.CharField(choices=[('TL', 'Teamlead'), ('BE', 'Backend'), ('FE', 'Frontend'), ('DS', 'Дизайн'), ('AL', 'Аналитика')], max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='specialization_2',
            field=models.CharField(choices=[('TL', 'Teamlead'), ('BE', 'Backend'), ('FE', 'Frontend'), ('DS', 'Дизайн'), ('AL', 'Аналитика')], max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='specialization_3',
            field=models.CharField(choices=[('TL', 'Teamlead'), ('BE', 'Backend'), ('FE', 'Frontend'), ('DS', 'Дизайн'), ('AL', 'Аналитика')], max_length=20),
        ),
    ]
