# Generated by Django 5.0.4 on 2024-04-24 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_userprofile_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='status',
            field=models.CharField(choices=[('Проектант', 'Проектант'), ('Наставник', 'Наставник')], default='Проектант', max_length=20),
        ),
    ]
