# Generated by Django 5.0.4 on 2024-04-24 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_alter_userprofile_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='description',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='specialization_1',
            field=models.CharField(blank=True, choices=[('TL', 'Teamlead'), ('BE', 'Backend'), ('FE', 'Frontend'), ('DS', 'Дизайн'), ('AL', 'Аналитика')], max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='specialization_2',
            field=models.CharField(blank=True, choices=[('TL', 'Teamlead'), ('BE', 'Backend'), ('FE', 'Frontend'), ('DS', 'Дизайн'), ('AL', 'Аналитика')], max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='specialization_3',
            field=models.CharField(blank=True, choices=[('TL', 'Teamlead'), ('BE', 'Backend'), ('FE', 'Frontend'), ('DS', 'Дизайн'), ('AL', 'Аналитика')], max_length=20),
        ),
    ]
