# Generated by Django 5.0.4 on 2024-05-01 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_userprofile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='specialization_4',
            field=models.CharField(blank=True, choices=[('Teamlead', 'Teamlead'), ('Backend', 'Backend'), ('Frontend', 'Frontend'), ('Дизайн', 'Дизайн'), ('Аналитика', 'Аналитика')], max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='specialization_5',
            field=models.CharField(blank=True, choices=[('Teamlead', 'Teamlead'), ('Backend', 'Backend'), ('Frontend', 'Frontend'), ('Дизайн', 'Дизайн'), ('Аналитика', 'Аналитика')], max_length=20),
        ),
        migrations.AlterField(
            model_name='question',
            name='specialization_1',
            field=models.CharField(choices=[('Teamlead', 'Teamlead'), ('Backend', 'Backend'), ('Frontend', 'Frontend'), ('Дизайн', 'Дизайн'), ('Аналитика', 'Аналитика')], max_length=20),
        ),
        migrations.AlterField(
            model_name='question',
            name='specialization_2',
            field=models.CharField(choices=[('Teamlead', 'Teamlead'), ('Backend', 'Backend'), ('Frontend', 'Frontend'), ('Дизайн', 'Дизайн'), ('Аналитика', 'Аналитика')], max_length=20),
        ),
        migrations.AlterField(
            model_name='question',
            name='specialization_3',
            field=models.CharField(choices=[('Teamlead', 'Teamlead'), ('Backend', 'Backend'), ('Frontend', 'Frontend'), ('Дизайн', 'Дизайн'), ('Аналитика', 'Аналитика')], max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='specialization_1',
            field=models.CharField(blank=True, choices=[('Teamlead', 'Teamlead'), ('Backend', 'Backend'), ('Frontend', 'Frontend'), ('Дизайн', 'Дизайн'), ('Аналитика', 'Аналитика')], max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='specialization_2',
            field=models.CharField(blank=True, choices=[('Teamlead', 'Teamlead'), ('Backend', 'Backend'), ('Frontend', 'Frontend'), ('Дизайн', 'Дизайн'), ('Аналитика', 'Аналитика')], max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='specialization_3',
            field=models.CharField(blank=True, choices=[('Teamlead', 'Teamlead'), ('Backend', 'Backend'), ('Frontend', 'Frontend'), ('Дизайн', 'Дизайн'), ('Аналитика', 'Аналитика')], max_length=20),
        ),
    ]
