# Generated by Django 5.0.4 on 2024-05-07 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_userprofile_specialization_4_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='photo',
            field=models.ImageField(blank=True, default='default_avatar.jpeg', upload_to='users_photo/'),
        ),
    ]
