# Generated by Django 5.0.4 on 2024-05-12 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_commentary_datetime_question_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='specialization_1',
        ),
        migrations.RemoveField(
            model_name='question',
            name='specialization_2',
        ),
        migrations.RemoveField(
            model_name='question',
            name='specialization_3',
        ),
    ]
