# Generated by Django 5.0.4 on 2024-05-12 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_remove_question_specialization_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentary',
            name='has_parent',
        ),
        migrations.RemoveField(
            model_name='commentary',
            name='parent',
        ),
    ]
