# Generated by Django 5.0.4 on 2024-05-14 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_remove_commentary_has_parent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_new',
            field=models.BooleanField(default=True),
        ),
    ]
