# Generated by Django 5.0.4 on 2024-05-14 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_question_comments_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='datetime',
            field=models.DateTimeField(blank=True),
        ),
    ]
