# Generated by Django 5.0.4 on 2024-05-14 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_alter_question_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentary',
            name='datetime',
            field=models.DateTimeField(),
        ),
    ]
