# Generated by Django 5.0.4 on 2024-12-05 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0020_consultation_date_consultation_time_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Question',
            new_name='ConsultationRequest',
        ),
        migrations.RenameField(
            model_name='commentary',
            old_name='question',
            new_name='ConsultationRequest',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='question',
            new_name='ConsultationRequest',
        ),
    ]
