# Generated by Django 5.0.4 on 2024-06-03 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0020_day_week'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='day',
            name='time_21to22',
            field=models.CharField(choices=[('Свободно', 'Свободно'), ('Недоступно', 'Недоступно'), ('Занято', 'Занято')], default='Недоступно', max_length=15),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='have_schedule',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='week',
            name='is_schedule',
            field=models.BooleanField(default=False),
        ),
    ]
