# Generated by Django 5.0.4 on 2024-06-03 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0021_day_date_day_time_21to22_userprofile_have_schedule_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='week',
            name='friday',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='backend.day'),
        ),
        migrations.AlterField(
            model_name='week',
            name='monday',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='backend.day'),
        ),
        migrations.AlterField(
            model_name='week',
            name='saturday',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='backend.day'),
        ),
        migrations.AlterField(
            model_name='week',
            name='sunday',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='backend.day'),
        ),
        migrations.AlterField(
            model_name='week',
            name='thursday',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='backend.day'),
        ),
        migrations.AlterField(
            model_name='week',
            name='tuesday',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='backend.day'),
        ),
        migrations.AlterField(
            model_name='week',
            name='wednesday',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='backend.day'),
        ),
    ]
