# Generated by Django 5.0.4 on 2024-12-05 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0022_remove_like_comment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='comments_count',
        ),
        migrations.RemoveField(
            model_name='application',
            name='is_new',
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('Активна', 'Активна'), ('Обработана', 'Обработана')], default='Активна', max_length=20),
        ),
    ]
