# Generated by Django 5.0.4 on 2024-06-03 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0023_alter_week_friday_alter_week_monday_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='time',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
