# Generated by Django 5.0.4 on 2024-12-09 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0023_remove_application_comments_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='likes',
        ),
    ]
