# Generated by Django 5.0.4 on 2024-06-03 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0024_consultation_date_consultation_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='time',
            field=models.CharField(max_length=10),
        ),
    ]
