# Generated by Django 5.0.4 on 2024-12-09 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0025_remove_application_author_application_sender_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='target',
        ),
        migrations.AddField(
            model_name='application',
            name='reciever',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='application_reciever', to='backend.userprofile'),
        ),
        migrations.AlterField(
            model_name='application',
            name='type',
            field=models.CharField(choices=[('Общая', 'Общая'), ('Личная', 'Личная')], default='Общая', max_length=20),
        ),
        migrations.DeleteModel(
            name='Consultation',
        ),
    ]
