# Generated by Django 5.0.4 on 2024-06-03 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0026_day_created_for_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='day',
            old_name='created_for_user',
            new_name='user',
        ),
    ]
