# Generated by Django 5.0.4 on 2024-12-18 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0026_remove_application_target_application_reciever_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('Активна', 'Активна'), ('Принята', 'Принята'), ('Отказано', 'Отказано')], default='Активна', max_length=20),
        ),
    ]
