# Generated by Django 5.0.4 on 2024-12-18 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0027_alter_application_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='mentor_comment',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
