# Generated by Django 5.0.4 on 2024-06-14 11:17

import backend.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0028_alter_week_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='day',
            name='user',
        ),
        migrations.AlterField(
            model_name='week',
            name='friday',
            field=models.OneToOneField(default=backend.models.Day.get_default_pk, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='week_friday', to='backend.day'),
        ),
        migrations.AlterField(
            model_name='week',
            name='monday',
            field=models.OneToOneField(default=backend.models.Day.get_default_pk, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='week_monday', to='backend.day'),
        ),
        migrations.AlterField(
            model_name='week',
            name='saturday',
            field=models.OneToOneField(default=backend.models.Day.get_default_pk, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='week_saturday', to='backend.day'),
        ),
        migrations.AlterField(
            model_name='week',
            name='sunday',
            field=models.OneToOneField(default=backend.models.Day.get_default_pk, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='week_sunday', to='backend.day'),
        ),
        migrations.AlterField(
            model_name='week',
            name='thursday',
            field=models.OneToOneField(default=backend.models.Day.get_default_pk, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='week_thursday', to='backend.day'),
        ),
        migrations.AlterField(
            model_name='week',
            name='tuesday',
            field=models.OneToOneField(default=backend.models.Day.get_default_pk, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='week_tuesday', to='backend.day'),
        ),
        migrations.AlterField(
            model_name='week',
            name='wednesday',
            field=models.OneToOneField(default=backend.models.Day.get_default_pk, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='week_wednesday', to='backend.day'),
        ),
    ]
