# Generated by Django 5.0.4 on 2025-01-11 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0029_userprofile_is_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='MentorApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university', models.CharField(max_length=200)),
                ('faculty', models.CharField(max_length=200)),
                ('specialization', models.CharField(max_length=200)),
                ('skills', models.TextField(max_length=5000)),
                ('status', models.CharField(choices=[('Активна', 'Активна'), ('Принята', 'Принята'), ('Отказано', 'Отказано')], max_length=200)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.userprofile')),
            ],
        ),
    ]
