# Generated by Django 5.0.4 on 2024-06-14 11:21

import backend.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0029_remove_day_user_alter_week_friday_alter_week_monday_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='week',
            name='friday',
            field=models.OneToOneField(default=backend.models.Day.get_default_pk, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='backend.day'),
        ),
        migrations.AlterField(
            model_name='week',
            name='monday',
            field=models.OneToOneField(default=backend.models.Day.get_default_pk, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='backend.day'),
        ),
        migrations.AlterField(
            model_name='week',
            name='saturday',
            field=models.OneToOneField(default=backend.models.Day.get_default_pk, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='backend.day'),
        ),
        migrations.AlterField(
            model_name='week',
            name='sunday',
            field=models.OneToOneField(default=backend.models.Day.get_default_pk, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='backend.day'),
        ),
        migrations.AlterField(
            model_name='week',
            name='thursday',
            field=models.OneToOneField(default=backend.models.Day.get_default_pk, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='backend.day'),
        ),
        migrations.AlterField(
            model_name='week',
            name='tuesday',
            field=models.OneToOneField(default=backend.models.Day.get_default_pk, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='backend.day'),
        ),
        migrations.AlterField(
            model_name='week',
            name='wednesday',
            field=models.OneToOneField(default=backend.models.Day.get_default_pk, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='backend.day'),
        ),
    ]
