# Generated by Django 5.0.4 on 2025-01-11 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0030_mentorapplication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentorapplication',
            name='faculty',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='mentorapplication',
            name='status',
            field=models.CharField(choices=[('Активна', 'Активна'), ('Принята', 'Принята'), ('Отказано', 'Отказано')], default='Активна', max_length=200),
        ),
    ]
