# Generated by Django 5.0.4 on 2024-11-17 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0031_day_user_alter_week_friday_alter_week_monday_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='telegram',
            field=models.CharField(default='tg', max_length=50),
            preserve_default=False,
        ),
    ]
