# Generated by Django 5.0.4 on 2025-01-11 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0031_alter_mentorapplication_faculty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorapplication',
            name='datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
