# Generated by Django 5.0.4 on 2025-01-11 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0032_mentorapplication_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentorapplication',
            name='datetime',
            field=models.DateTimeField(blank=True),
        ),
    ]
