# Generated by Django 5.0.4 on 2024-04-24 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_ts1', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserData',
        ),
    ]
